### ISSUE TITLE
More of a suggestion.

### ISSUE THREAD

**Issue by gusman21** [shrocky2/SiriGarage#1]
Hello,

Great project. As a suggestion I'd recommend changing the pin field for door operation and the field for admin logon to input type="password" as to prevent autocomplete and prying eyes.

Keep up the great projects!!

**Comment by shrocky2** [comment]
The password idea can easily be changed in on lines 16 & 17 of the SiriGarage/static/admin_login.html page.

Since this project is open source, you can edit all these files on your raspberry pi using "sudo nano SiriGarage/static/admin_login.html"

**Comment by gusman21** [comment]
I did make these changes. I was just suggesting it for your project as
well. Thanks.
