### ISSUE TITLE
Curl command to open/close a door?

### ISSUE THREAD

**Issue by snagglewest** [shrocky2/SiriGarage#12]
Thank you so much for sharing this project, it was easy to set up tweak to our needs. We’ve bee using it for several years for our 2 garage doors and I even took door 3 and use it to monitor the exterior door for open/close.

I'm wondering if you might be able to answer a question?  We’ve started to use Home Assistant for your smart home stuff and I was able to incorporate the position of the doors by parsing a curl command (curl http://[IPAdDRESS]:5000/Siri/GarageDoorStatus?).

I'd like to automate the opening and closing of the doors and I figured another curl command would be easy. I'm not a programmer by any stretch but I picked thru your code and I think I might be close but no joy.  I've tried lots of variations of this to no avail.

curl -s http://[IPADDRESS]:5000/Siri/GarageDoorStatus?method=post&ps=[PASSWORD]&Door=Door1&dowhat=Open

So my question is - is it possible to send a curl command to open or close a door and if so would you mind giving me an example?  Or maybe I’m so focused on curl there might be another way?

I would be very grateful for any help you might be willing to share!

**Comment by shrocky2** [comment]
It should be possible with the curl command. I don’t use curl very often, so I had to do a little research.

My project uses a POST command to send data to the web server. The curl command by default uses a GET command. So when you make a curl command, you are telling your computer to go and GET the webpage for the URL your provided.

You need to tell curl to POST (or send) some data to the server to process. I would try code like this:

curl -d ‘ps=[PASSWORD]&door=Door1&dowhat=Open’ http://[IPADDRESS]:5000/Siri/Garage

If that doesn’t work, try adding a “-X POST” into that code. But that shouldn’t be needed.

curl -X POST -d ‘ps=[PASSWORD]&door=Door1&dowhat=Open’ http://[IPADDRESS]:5000/Siri/Garage

Go luck.

PS, the address you sent (http://[IPAdDRESS]:5000/Siri/GarageDoorStatus) only checks the status of the garage door, that address will not open or close the doors

**Comment by snagglewest** [comment]
Success!
curl -d 'ps=[password]&door=Door1&dowhat=Close' http://[IPADDRESS]:5001/Siri/Garage?

Thanks so much again for sharing this awesome project.  There's lots Rpi garage door opener projects out there but yours is by far the most user friendly and polished.  Even my tech adverse wife loves it and that's saying a lot!
