### ISSUE TITLE
Pin Mapping Issue

### ISSUE THREAD

**Issue by cspeltz** [shrocky2/SiriGarage#2]
Great project. I implemented it in my own home over the weekend. I was having issues, and I think they were coming from the GPIO pins to the relays.  They are mislabeled in the jpg diagram, but I think they are correct in the code.

**Comment by shrocky2** [comment]
Thanks for letting me know. The image was correct, but I labeled them incorrectly. I've updated the picture with the correct labels. Thanks again!
