### ISSUE TITLE
log.py issue

### ISSUE THREAD

**Issue by rhubarbo** [shrocky2/SiriGarage#4]
Log.py: 

Lines 72-90 should have one indent removed. 

In the current state, no data for Door #1 will be logged as Line 63 presents a contrary condition.

**Comment by shrocky2** [comment]
Thanks for bringing this mistake to my attention. I was missing a line that should have been on line 72. The missing line was a  "else:" statement. If you look at code for Door 2 and Door 3, they now all match.
